name: Stage Deployment

on:
  workflow_dispatch:
jobs:
  build:
    if: contains('["Manthan-Thakkar","lpoulter"]', github.actor)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_TAG: $(echo ${{ github.sha }} | cut -c 1-8)
    environment: staging
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.13
    - name: Short SHA
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: get releases
      run: |
        mkdir /hello_world
        touch hello_world/manthan.txt
        ls hello_world
        ls -a hello_world
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        echo $IMAGE_TAG
        node -v
        npm -v
        curl https://api.ipify.org/
        env
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.3
      with:
        owner: Manthan-Thakkar
        repo: springboot-workflow-ecs
