name: Stage Deployment

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: $(echo ${{ github.sha }} | cut -c 1-8)
    environment: staging
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.13
    - name: Short SHA
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        echo $IMAGE_TAG
        node -v
        npm -v
